<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 2 Choosing and evaluating models | Practical Data Science with R - Tidyverse style</title>
  <meta name="description" content="These are my notes while reading the book Practical Data Science with R - Tidyverse style">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 2 Choosing and evaluating models | Practical Data Science with R - Tidyverse style" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These are my notes while reading the book Practical Data Science with R - Tidyverse style" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Choosing and evaluating models | Practical Data Science with R - Tidyverse style" />
  
  <meta name="twitter:description" content="These are my notes while reading the book Practical Data Science with R - Tidyverse style" />
  

<meta name="author" content="Indrajeet Patil">


<meta name="date" content="2019-02-24">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">"Practical Data Science with R - Tidyverse style"</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="choosing-and-evaluating-models.html"><a href="choosing-and-evaluating-models.html"><i class="fa fa-check"></i><b>2</b> Choosing and evaluating models</a><ul>
<li class="chapter" data-level="2.1" data-path="choosing-and-evaluating-models.html"><a href="choosing-and-evaluating-models.html#building-and-applying-a-logistic-regression-spam-model"><i class="fa fa-check"></i><b>2.1</b> Building and applying a logistic regression spam model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Practical Data Science with R - Tidyverse style</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="choosing-and-evaluating-models" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Choosing and evaluating models</h1>
<div id="building-and-applying-a-logistic-regression-spam-model" class="section level2">
<h2><span class="header-section-number">2.1</span> Building and applying a logistic regression spam model</h2>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">123</span>)
<span class="kw">library</span>(tidyverse, <span class="dt">warn.conflicts =</span> <span class="ot">FALSE</span>)</code></pre>
<p>Using logistic regression to classify emails into spam or non-spam:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># reading the file containing spam data</span>
spamD &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_tsv</span>(<span class="st">&quot;https://raw.githubusercontent.com/WinVector/zmPDSwR/master/Spambase/spamD.tsv&quot;</span>)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   spam = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># creating training and testing datasets</span>
spamTrain &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(<span class="dt">.data =</span> spamD, rgroup <span class="op">&gt;=</span><span class="st"> </span><span class="dv">10</span>)
spamTest &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">filter</span>(<span class="dt">.data =</span> spamD, rgroup <span class="op">&lt;</span><span class="st"> </span><span class="dv">10</span>)

<span class="co"># training the model</span>
spamModel &lt;-<span class="st"> </span>stats<span class="op">::</span><span class="kw">glm</span>(<span class="dt">formula =</span> spam <span class="op">==</span><span class="st">&quot;spam&quot;</span> <span class="op">~</span><span class="st"> </span>.,
           <span class="dt">family =</span> stats<span class="op">::</span><span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>),
           <span class="dt">data =</span> dplyr<span class="op">::</span><span class="kw">select</span>(spamTrain, <span class="op">-</span>rgroup))</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># looking at the result</span>
broom<span class="op">::</span><span class="kw">tidy</span>(spamModel)</code></pre>
<pre><code>## # A tibble: 58 x 5
##    term               estimate std.error statistic  p.value
##    &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 (Intercept)          -1.62     0.151     -10.7  1.24e-26
##  2 word.freq.make       -0.327    0.237      -1.38 1.68e- 1
##  3 word.freq.address    -0.155    0.0771     -2.00 4.51e- 2
##  4 word.freq.all         0.149    0.123       1.22 2.23e- 1
##  5 word.freq.3d          2.19     1.56        1.40 1.60e- 1
##  6 word.freq.our         0.476    0.102       4.68 2.91e- 6
##  7 word.freq.over        0.744    0.252       2.95 3.13e- 3
##  8 word.freq.remove      2.34     0.349       6.70 2.08e-11
##  9 word.freq.internet    0.801    0.220       3.63 2.83e- 4
## 10 word.freq.order       0.645    0.300       2.15 3.14e- 2
## # ... with 48 more rows</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># looking at the model summary</span>
broom<span class="op">::</span><span class="kw">glance</span>(spamModel)</code></pre>
<pre><code>## # A tibble: 1 x 7
##   null.deviance df.null logLik   AIC   BIC deviance df.residual
##           &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;
## 1         5556.    4142  -807. 1730. 2097.    1614.        4085</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># with predicted response on training data</span>
spamTrain &lt;-<span class="st"> </span>broom<span class="op">::</span><span class="kw">augment</span>(
  <span class="dt">x =</span> spamModel,
  <span class="dt">newdata =</span> spamTrain,
  <span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>
)

<span class="co"># with predicted response on test data</span>
spamTest &lt;-<span class="st"> </span>broom<span class="op">::</span><span class="kw">augment</span>(
  <span class="dt">x =</span> spamModel,
  <span class="dt">newdata =</span> spamTest,
  <span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>
)

<span class="co"># performance with the training data</span>
train_perform &lt;-<span class="st"> </span><span class="kw">table</span>(<span class="dt">y =</span> spamTrain<span class="op">$</span>spam, <span class="dt">glmPred =</span> spamTrain<span class="op">$</span>.fitted <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>)

<span class="co"># performance with the test data</span>
test_perform &lt;-<span class="st"> </span><span class="kw">table</span>(<span class="dt">y =</span> spamTest<span class="op">$</span>spam, <span class="dt">glmPred =</span> spamTest<span class="op">$</span>.fitted <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>) </code></pre>
<p>Looking at actual and predicted sample responses</p>
<pre class="sourceCode r"><code class="sourceCode r">sample &lt;-<span class="st"> </span>spamTest[<span class="kw">c</span>(<span class="dv">7</span>,<span class="dv">35</span>,<span class="dv">224</span>,<span class="dv">327</span>), <span class="kw">c</span>(<span class="st">&#39;spam&#39;</span>, <span class="st">&#39;.fitted&#39;</span>)]
<span class="kw">print</span>(sample)</code></pre>
<pre><code>## # A tibble: 4 x 2
##   spam      .fitted
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 spam     0.990   
## 2 spam     0.480   
## 3 non-spam 0.000685
## 4 non-spam 0.000143</code></pre>
<p>Spam confusion matrix (to assess performance of the model)</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># performance with the test data</span>
(cM &lt;-<span class="st"> </span><span class="kw">table</span>(<span class="dt">truth =</span> spamTest<span class="op">$</span>spam, <span class="dt">prediction =</span> spamTest<span class="op">$</span>.fitted <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>)) </code></pre>
<pre><code>##           prediction
## truth      FALSE TRUE
##   non-spam   264   14
##   spam        22  158</code></pre>
<p>Assessing the performance</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># chaning column names to align with rownames</span>
<span class="kw">colnames</span>(cM) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;non-spam&quot;</span>, <span class="st">&quot;spam&quot;</span>)

<span class="co"># looking at performance measures</span>
caret<span class="op">::</span><span class="kw">confusionMatrix</span>(cM)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           prediction
## truth      non-spam spam
##   non-spam      264   14
##   spam           22  158
##                                           
##                Accuracy : 0.9214          
##                  95% CI : (0.8928, 0.9443)
##     No Information Rate : 0.6245          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.834           
##  Mcnemar&#39;s Test P-Value : 0.2433          
##                                           
##             Sensitivity : 0.9231          
##             Specificity : 0.9186          
##          Pos Pred Value : 0.9496          
##          Neg Pred Value : 0.8778          
##              Prevalence : 0.6245          
##          Detection Rate : 0.5764          
##    Detection Prevalence : 0.6070          
##       Balanced Accuracy : 0.9208          
##                                           
##        &#39;Positive&#39; Class : non-spam        
## </code></pre>
<p>Entering data by hand (example of a good spam filter at WinVectorLLC blog)</p>
<pre class="sourceCode r"><code class="sourceCode r">t &lt;-<span class="st"> </span><span class="kw">as.table</span>(<span class="kw">matrix</span>(<span class="dt">data =</span> <span class="kw">c</span>(<span class="dv">288</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dv">17</span>, <span class="dv">1</span>, <span class="dv">13882</span> <span class="op">-</span><span class="st"> </span><span class="dv">17</span>), <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">ncol =</span> <span class="dv">2</span>))

<span class="kw">rownames</span>(t) &lt;-<span class="st"> </span><span class="kw">rownames</span>(cM)
<span class="kw">colnames</span>(t) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;non-spam&quot;</span>, <span class="st">&quot;spam&quot;</span>)

<span class="co"># looking at performance measures</span>
caret<span class="op">::</span><span class="kw">confusionMatrix</span>(t)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##          non-spam  spam
## non-spam      287     1
## spam           17 13865
##                                          
##                Accuracy : 0.9987         
##                  95% CI : (0.998, 0.9992)
##     No Information Rate : 0.9785         
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
##                                          
##                   Kappa : 0.9689         
##  Mcnemar&#39;s Test P-Value : 0.000407       
##                                          
##             Sensitivity : 0.94408        
##             Specificity : 0.99993        
##          Pos Pred Value : 0.99653        
##          Neg Pred Value : 0.99878        
##              Prevalence : 0.02145        
##          Detection Rate : 0.02025        
##    Detection Prevalence : 0.02032        
##       Balanced Accuracy : 0.97200        
##                                          
##        &#39;Positive&#39; Class : non-spam       
## </code></pre>
<p>Accuracy for our <code>glm</code>-based classifier was 92.14%, while it’s 99.87% for a good
classifier.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["PDSwR.pdf", "PDSwR.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
